services:
  postgres:
    image: postgres:16-alpine
    container_name: foodies-database
    environment:
      POSTGRES_DB: foodies-database
      POSTGRES_USER: foodies_admin
      POSTGRES_PASSWORD: foodies_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
