services:
  postgres-profile:
    image: postgres:18-alpine
    container_name: foodies-profile-database
    environment:
      POSTGRES_DB: foodies-profile-database
      POSTGRES_USER: foodies_admin
      POSTGRES_PASSWORD: foodies_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-menu:
    image: postgres:18-alpine
    container_name: foodies-menu-database
    environment:
      POSTGRES_DB: foodies-menu-database
      POSTGRES_USER: foodies_admin
      POSTGRES_PASSWORD: foodies_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_menu_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: foodies-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:8-alpine
    container_name: foodies-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.1
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm.json
      - KC_HTTP_PORT=8000
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE:-profile.registration}
    ports:
      - "8000:8000"
    volumes:
      - ./keycloak:/opt/keycloak/data/import/
      - ./keycloak-rabbitmq-publisher/build/libs:/opt/keycloak/providers
    depends_on:
      - rabbitmq
    command:
      - start-dev
      - --import-realm

  menu:
    image: menu:0.0.1
    container_name: foodies-menu
    environment:
      - DB_URL=jdbc:postgresql://postgres-menu:5432/foodies-menu-database
      - RABBITMQ_HOST=rabbitmq
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - postgres-menu
      - rabbitmq

  basket:
    image: basket:0.0.6
    container_name: foodies-basket
    ports:
      - "8083:8083" # Using 8083 because the webapp is configured to reach it on 8083 (see application.yaml)
    environment:
      - AUTH_ISSUER=http://keycloak:8000/realms/foodies-keycloak
      - REDIS_HOST=redis
      - MENU_SERVICE_URL=http://menu:8080
      - RABBITMQ_HOST=rabbitmq
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - redis
      - rabbitmq

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: otel-collector
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./k8s/base/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  webapp:
    image: webapp:0.0.3
    container_name: foodies-webapp
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_BASE_URL=http://keycloak:8000
      - AUTH_ISSUER=http://keycloak:8000/realms/foodies-keycloak
      - MENU_BASE_URL=http://menu:8080
      - BASKET_BASE_URL=http://basket:8083
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - redis
      - keycloak
      - menu
      - basket
      - otel-collector

volumes:
  postgres_data:
  postgres_menu_data:
  redis_data:
