services:
  postgres-profile:
    image: postgres:18-alpine
    container_name: foodies-profile-database
    environment:
      POSTGRES_DB: foodies-profile-database
      POSTGRES_USER: foodies_admin
      POSTGRES_PASSWORD: foodies_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-menu:
    image: postgres:18-alpine
    container_name: foodies-menu-database
    environment:
      POSTGRES_DB: foodies-menu-database
      POSTGRES_USER: foodies_admin
      POSTGRES_PASSWORD: foodies_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_menu_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: foodies-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: foodies-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm.json
      - KC_HTTP_PORT=8000
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE:-profile.registration}
    ports:
      - "8000:8000"
    volumes:
      - ./keycloak:/opt/keycloak/data/import/
      - ./keycloak-rabbitmq-publisher/build/libs:/opt/keycloak/providers
    depends_on:
      - rabbitmq
    command:
      - start-dev
      - --import-realm

volumes:
  postgres_data:
  postgres_menu_data:
  redis_data:
