config:
  host: "$HOST:0.0.0.0"
  port: "$PORT:8081"
  data_source:
    url: "$DB_URL:jdbc:postgresql://localhost:5432/foodies-profile-database"
    username: "$DB_USERNAME:foodies_admin"
    password: "$DB_PASSWORD:foodies_password"
  rabbit:
    host: "$RABBITMQ_HOST:localhost"
    port: "$RABBITMQ_PORT:5672"
    username: "$RABBITMQ_USERNAME:profile"
    password: "$RABBITMQ_PASSWORD:profile-password"
    queue: "$RABBITMQ_QUEUE:profile.registration"
  telemetry:
    otlp_endpoint: "$OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317"