config:
  host: "$HOST:0.0.0.0"
  port: "$PORT:8080"
  data_source:
    url: "$DB_URL:jdbc:postgresql://localhost:5432/foodies-profile-database"
    username: "$DB_USERNAME:foodies_admin"
    password: "$DB_PASSWORD:foodies_password"