config:
  host: "$HOST:0.0.0.0"
  port: "$PORT:8081"
  auth:
    issuer: "$AUTH_ISSUER:http://localhost:9090/realms/foodies-keycloak"
    service_audience: "$SERVICE_AUDIENCE:profile-service"
    user_audience: "$USER_AUDIENCE:profile-service"
  data_source:
    url: "$DB_URL:jdbc:postgresql://localhost:5432/foodies-profile-database"
    username: "$DB_USERNAME:foodies_admin"
    password: "$DB_PASSWORD:foodies_password"
  rabbit:
    host: "$RABBITMQ_HOST:localhost"
    port: "$RABBITMQ_PORT:5672"
    username: "$RABBITMQ_USERNAME:guest"
    password: "$RABBITMQ_PASSWORD:guest"
    queue: "$RABBITMQ_QUEUE:profile.registration"
  telemetry:
    otlp_endpoint: "$OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317"