apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/rabbitmq-operator
  - ../../base/cert-manager
  - ../../base

configMapGenerator:
  - name: foodies-config
    behavior: merge
    literals:
      - FOODIES_HOST=foodies.com
  - name: keycloak-realm
    behavior: merge
    files:
      - keycloak/realm-prod.json

secretGenerator:
  - name: keycloak-admin
    behavior: merge
    literals:
      - KC_BOOTSTRAP_ADMIN_PASSWORD=change-me-at-runtime
  - name: postgres-credentials
    behavior: merge
    literals:
      - POSTGRES_PASSWORD=change-me-at-runtime
  - name: webapp-auth
    behavior: merge
    literals:
      - AUTH_CLIENT_SECRET=change-me-at-runtime

patches:
  - target:
      kind: Deployment
      name: webapp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Ingress
      name: foodies-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: foodies.com
  - target:
      kind: PersistentVolumeClaim
      name: redis-data
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: standard
  - target:
      kind: PersistentVolumeClaim
      name: prometheus-data
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: standard
  - target:
      kind: RabbitmqCluster
      name: rabbitmq
    patch: |-
      - op: add
        path: /spec/persistence/storageClassName
        value: standard
  - target:
      kind: StatefulSet
      name: profile-postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: standard
  - target:
      kind: StatefulSet
      name: menu-postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: standard
  - target:
      kind: StatefulSet
      name: order-postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: standard
  - target:
      kind: StatefulSet
      name: payment-postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: standard
  - target:
      kind: StatefulSet
      name: keycloak-postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: standard
  - target:
      kind: Job
      name: keycloak-config-cli
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: webapp-auth
              key: AUTH_CLIENT_SECRET
