apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-config-cli
  namespace: foodies
  labels:
    app: keycloak-config-cli
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: keycloak-config-cli
    spec:
      restartPolicy: OnFailure
      containers:
        - name: keycloak-config-cli
          image: quay.io/adorsys/keycloak-config-cli:latest
          env:
            - name: KEYCLOAK_URL
              value: http://keycloak:8000/auth
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: KC_BOOTSTRAP_ADMIN_USERNAME
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: KC_BOOTSTRAP_ADMIN_PASSWORD
            - name: IMPORT_FILES_LOCATIONS
              value: /config/*.json
            - name: IMPORT_FORCE
              value: "true"
            - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
              value: "true"
            - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
              value: 240S
          volumeMounts:
            - name: keycloak-realm
              mountPath: /config
      volumes:
        - name: keycloak-realm
          configMap:
            name: keycloak-realm
