apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak.yaml
  - keycloak-cr.yaml
  - keycloak-realm-import-cr.yaml
  - database.yaml

configMapGenerator:
  - name: keycloak-config
    literals:
      - KC_HOSTNAME_STRICT=true
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HTTP_MANAGEMENT_RELATIVE_PATH=/
      - KC_PROXY_HEADERS=xforwarded
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
