apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-template
data:
  realm-template.json: |
    {
      "realm": "foodies-keycloak",
      "enabled": true,
      "registrationAllowed": true,
      "resetPasswordAllowed": true,
      "eventsEnabled": true,
      "eventsListeners": ["jboss-logging", "profile-webhook"],
      "enabledEventTypes": ["REGISTER", "DELETE_ACCOUNT", "UPDATE_PROFILE"],
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "Regular user with standard permissions"
          }
        ]
      },
      "clientScopes": [
        {
          "name": "foodies-audience",
          "description": "Adds foodies audience to tokens for API access",
          "protocol": "openid-connect",
          "attributes": {
            "include.in.token.scope": "false",
            "display.on.consent.screen": "false"
          },
          "protocolMappers": [
            {
              "name": "audience-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "foodies",
                "id.token.claim": "true",
                "access.token.claim": "true"
              }
            }
          ]
        }
      ],
      "clients": [
        {
          "clientId": "foodies",
          "directAccessGrantsEnabled": true,
          "publicClient": false,
          "secret": "${KEYCLOAK_CLIENT_SECRET}",
          "redirectUris": ["http://${FOODIES_HOST}/oauth/callback"],
          "webOrigins": ["http://${FOODIES_HOST}"],
          "defaultClientScopes": ["foodies-audience"],
          "attributes": {
            "post.logout.redirect.uris": "http://${FOODIES_HOST}/"
          }
        }
      ],
      "users": [
        {
          "username": "food3_lover",
          "enabled": true,
          "email": "food_lover@gmail.com",
          "firstName": "Food",
          "lastName": "Lover",
          "credentials": [
            {
              "type": "password",
              "value": "${KEYCLOAK_TEST_USER_PASSWORD}",
              "temporary": false
            }
          ],
          "realmRoles": ["user"]
        }
      ]
    }
