env:
  host: "0.0.0.0"
  port: 8080
  data_source:
    url: "$DB_URL:jdbc:postgresql://localhost:5432/foodies-database"
    username: "$DB_USERNAME:foodies_admin"
    password: "$DB_PASSWORD:foodies_password"