apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: webapp-config
    literals:
      - HOST=0.0.0.0
      - PORT=8080
      - AUTH_ISSUER=http://keycloak:8000/realms/foodies-keycloak
      - AUTH_CLIENT_ID=foodies
      - MENU_BASE_URL=http://menu:8082
      - BASKET_BASE_URL=http://basket:8083
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_TTL_SECONDS=3600
