[versions]
kotlin = "2.3.0"
logback = "1.5.24"
exposed = "1.0.0-rc-4"
hikari = "7.0.2"
postgresql = "42.7.8"
testcontainers = "1.21.4"
flyway = "11.20.1"
micrometer = "1.16.1"
testballoon = "0.7.1-K2.3.0"
keycloak = "26.5.0"
rabbitmq = "5.28.0"
serialization="1.10.0-RC"
shadow = "9.3.1"
cohort = "2.8.2"
lettuce = "6.5.5.RELEASE"
redis-testcontainers = "2.2.4"
kotlinx-coroutines = "1.10.2"
playwright = "1.49.0"
keycloak-testcontainers = "3.4.0"
opentelemetry = "1.47.0"

[libraries]
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testballoon = { module = "de.infix.testBalloon:testBalloon-framework-core", version.ref = "testballoon" }
keycloak-core = { module = "org.keycloak:keycloak-core", version.ref = "keycloak" }
keycloak-services = { module = "org.keycloak:keycloak-services", version.ref = "keycloak" }
keycloak-server-spi = { module = "org.keycloak:keycloak-server-spi", version.ref = "keycloak" }
keycloak-server-spi-private = { module = "org.keycloak:keycloak-server-spi-private", version.ref = "keycloak" }
rabbitmq = { module = "com.rabbitmq:amqp-client", version.ref = "rabbitmq" }
testcontainers-rabbitmq = { module = "org.testcontainers:rabbitmq", version.ref = "testcontainers" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
cohort-ktor = { module = "com.sksamuel.cohort:cohort-ktor", version.ref = "cohort" }
cohort-hikari = { module = "com.sksamuel.cohort:cohort-hikari", version.ref = "cohort" }
cohort-api = { module = "com.sksamuel.cohort:cohort-api", version.ref = "cohort" }
cohort-lettuce = { module = "com.sksamuel.cohort:cohort-lettuce", version.ref = "cohort" }
lettuce = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-redis = { module = "com.redis:testcontainers-redis", version.ref = "redis-testcontainers" }
testcontainers-keycloak = { module = "com.github.dasniko:testcontainers-keycloak", version.ref = "keycloak-testcontainers" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
playwright = { module = "com.microsoft.playwright:playwright", version.ref = "playwright" }

otel-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
otel-sdk = { module = "io.opentelemetry:opentelemetry-sdk", version.ref = "opentelemetry" }

otel-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp", version.ref = "opentelemetry" }
otel-ktor = { module = "io.opentelemetry.instrumentation:opentelemetry-ktor-3.0", version = "2.23.0-alpha" }
otel-hikari = { module = "io.opentelemetry.instrumentation:opentelemetry-hikaricp-3.0", version = "2.23.0-alpha" }
otel-jdbc = { module = "io.opentelemetry.instrumentation:opentelemetry-jdbc", version = "2.23.0-alpha" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
testballoon = { id = "de.infix.testBalloon", version.ref = "testballoon" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }