apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: foodies
spec:
  name: foodies
  type: topic
  durable: true
  vhost: /
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: foodies-dlx
spec:
  name: foodies.dlx
  type: topic
  durable: true
  vhost: /
  rabbitmqClusterReference:
    name: rabbitmq
