apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rabbitmq.yaml
  - statefulset.yaml

configMapGenerator:
  - name: rabbitmq-config
    files:
      - rabbitmq.conf
      - definitions.json
