apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml
  - users.yaml
  - permissions.yaml
  - queues.yaml
  - exchanges.yaml
  - bindings.yaml
  - policies.yaml
  - rabbitmq-secrets.yaml
