apiVersion: v1
kind: Secret
metadata:
  name: guest-user-credentials
type: Opaque
stringData:
  username: "guest"
  password: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: profile-service-credentials
type: Opaque
stringData:
  username: "profile-service"
  password: "profile_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: menu-service-credentials
type: Opaque
stringData:
  username: "menu-service"
  password: "menu_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: basket-service-credentials
type: Opaque
stringData:
  username: "basket-service"
  password: "basket_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-credentials
type: Opaque
stringData:
  username: "order-service"
  password: "order_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-credentials
type: Opaque
stringData:
  username: "payment-service"
  password: "payment_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-service-credentials
type: Opaque
stringData:
  username: "keycloak-service"
  password: "keycloak_password"
