apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
stringData:
  RABBITMQ_GUEST_PASSWORD: "guest"
  RABBITMQ_PROFILE_SERVICE_PASSWORD: "profile_password"
  RABBITMQ_MENU_SERVICE_PASSWORD: "menu_password"
  RABBITMQ_BASKET_SERVICE_PASSWORD: "basket_password"
  RABBITMQ_ORDER_SERVICE_PASSWORD: "order_password"
  RABBITMQ_PAYMENT_SERVICE_PASSWORD: "payment_password"
  RABBITMQ_KEYCLOAK_SERVICE_PASSWORD: "keycloak_password"
