apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: guest
spec:
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: guest-user-credentials
  tags:
  - administrator
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: profile-service
spec:
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: profile-service-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: menu-service
spec:
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: menu-service-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: basket-service
spec:
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: basket-service-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: order-service
spec:
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: order-service-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: payment-service
spec:
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: payment-service-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: keycloak-service
spec:
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: keycloak-service-credentials
