apiVersion: v1
kind: ConfigMap
metadata:
  name: foodies-config
  namespace: foodies
data:
  FOODIES_HOST: foodies.local
  PROFILE_DB_NAME: foodies-profile-database
  MENU_DB_NAME: foodies-menu-database
  RABBITMQ_QUEUE: profile.registration
  BASKET_RABBITMQ_QUEUE: basket.order-created
  KEYCLOAK_HTTP_PORT: "8000"
