config:
  host: "$HOST:0.0.0.0"
  port: "$PORT:8085"
  auth:
    issuer: "$AUTH_ISSUER:http://localhost:8000/realms/foodies-keycloak"
    service_audience: "payment-service"
    user_audience: "foodies"
  data_source:
    url: "$DB_URL:jdbc:postgresql://localhost:5434/foodies-payment-database"
    username: "$DB_USERNAME:foodies_admin"
    password: "$DB_PASSWORD:foodies_password"
  rabbit:
    host: "$RABBITMQ_HOST:localhost"
    port: "$RABBITMQ_PORT:5672"
    username: "$RABBITMQ_USERNAME:guest"
    password: "$RABBITMQ_PASSWORD:guest"
    consume_queue: "$RABBITMQ_CONSUME_QUEUE:payment.stock-confirmed"
    publish_exchange: "$RABBITMQ_PUBLISH_EXCHANGE:foodies.events"
  gateway:
    always_succeed: "$PAYMENT_ALWAYS_SUCCEED:true"
    processing_delay_ms: "$PAYMENT_DELAY_MS:100"
  telemetry:
    otlp_endpoint: "$OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317"
