config:
  host: "$HOST:0.0.0.0"
  port: "$PORT:8080"
  security:
    issuer: "$AUTH_ISSUER:http://localhost:8000/realms/foodies-keycloak"
    clientId: "$AUTH_CLIENT_ID:foodies"
    clientSecret: "$AUTH_CLIENT_SECRET:foodies_client_secret"
  menu:
    baseUrl: "$MENU_BASE_URL:http://localhost:8082"
  basket:
    baseUrl: "$BASKET_BASE_URL:http://localhost:8083"
  redis:
    host: "$REDIS_HOST:localhost"
    port: "$REDIS_PORT:6379"
    password: "$REDIS_PASSWORD:"
    ttlSeconds: "$SESSION_TTL_SECONDS:3600"
