apiVersion: v1
kind: Service
metadata:
  name: menu
  namespace: foodies
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: menu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu
  namespace: foodies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
        - name: menu
          image: foodies-menu:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8082"
            - name: DB_URL
              value: jdbc:postgresql://menu-postgres:5432/foodies-menu-database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
