apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foodies

resources:
  - namespace
  - ingress
  - basket
  - menu
  - order
  - payment
  - profile
  - rabbitmq
  - redis
  - webapp
  - keycloak
  - otel-collector
  - jaeger
  - prometheus

configMapGenerator:
  - name: foodies-config
    literals:
      - FOODIES_HOST=foodies.local
      - PROFILE_DB_NAME=foodies-profile-database
      - RABBITMQ_QUEUE=profile.registration
      - BASKET_RABBITMQ_QUEUE=basket.order-created
      - KEYCLOAK_HTTP_PORT=8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

secretGenerator:
  - name: keycloak-admin
    options:
      disableNameSuffixHash: true
    literals:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
  - name: postgres-credentials
    literals:
      - POSTGRES_USER=foodies_admin
      - POSTGRES_PASSWORD=foodies_password
  - name: rabbitmq-credentials
    literals:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
  - name: profile-rabbitmq-credentials
    literals:
      - RABBITMQ_USERNAME=profile_service
      - RABBITMQ_PASSWORD=ns7cmt245Wd4czlR14loCOQC/QkSNrR2p0hfPXVvQJE=
  - name: menu-rabbitmq-credentials
    literals:
      - RABBITMQ_USERNAME=menu_service
      - RABBITMQ_PASSWORD=fp4UnNJ4vcSHdBGAyxzA8av/rQ0/DCerX/0xlY9ctsA=
  - name: basket-rabbitmq-credentials
    literals:
      - RABBITMQ_USERNAME=basket_service
      - RABBITMQ_PASSWORD=i6BUFwm2GiNOhCRo/jhDS0Jz8/SfJsCdNORFB90MqTY=
  - name: order-rabbitmq-credentials
    literals:
      - RABBITMQ_USERNAME=order_service
      - RABBITMQ_PASSWORD=p7yNOuj/7vvGH6dkfIW+6gRPyYzUcC0eybZHqvPuuC0=
  - name: payment-rabbitmq-credentials
    literals:
      - RABBITMQ_USERNAME=payment_service
      - RABBITMQ_PASSWORD=JcFLK9E3SKhIOd92U88td2Aqww5T5m+QsHOucv0VRK8=
  - name: keycloak-rabbitmq-credentials
    literals:
      - RABBITMQ_USERNAME=keycloak_service
      - RABBITMQ_PASSWORD=MeZZEYsAyI8Ft2k+lmSiVsway6Sj5TO7X2HbOfQfbQo=
  - name: webapp-auth
    literals:
      - AUTH_CLIENT_SECRET=foodies_client_secret
