apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foodies

resources:
  - namespace
  - ingress
  - basket
  - menu
  - order
  - payment
  - profile
  - rabbitmq
  - redis
  - webapp
  - keycloak
  - otel-collector
  - jaeger
  - prometheus
  - secrets/keycloak-admin.yaml
  - secrets/postgres-credentials.yaml
  - secrets/rabbitmq-credentials.yaml
  - secrets/webapp-auth.yaml
  - secrets/order-service-credentials.yaml
  - secrets/basket-service-credentials.yaml
  - secrets/menu-service-credentials.yaml
  - secrets/payment-service-credentials.yaml
  - secrets/profile-service-credentials.yaml
  - secrets/order-rabbitmq-credentials.yaml
  - secrets/basket-rabbitmq-credentials.yaml
  - secrets/menu-rabbitmq-credentials.yaml
  - secrets/profile-rabbitmq-credentials.yaml
  - secrets/payment-rabbitmq-credentials.yaml
  - secrets/keycloak-rabbitmq-credentials.yaml

configMapGenerator:
  - name: foodies-config
    literals:
      - FOODIES_HOST=foodies.local
      - PROFILE_DB_NAME=foodies-profile-database
      - RABBITMQ_QUEUE=profile.registration
      - BASKET_RABBITMQ_QUEUE=basket.order-created
      - KEYCLOAK_HTTP_PORT=8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

