services:
  postgres:
    image: postgres:16-alpine
    container_name: foodies-database
    environment:
      POSTGRES_DB: foodies-database
      POSTGRES_USER: foodies_admin
      POSTGRES_PASSWORD: foodies_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm.json
      - KC_HTTP_PORT=8000
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    ports:
      - "8000:8000"
    volumes:
      - ./keycloak:/opt/keycloak/data/import/
    command:
      - start-dev
      - --import-realm

volumes:
  postgres_data:
