apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/rabbitmq-operator
  - ../../base/cert-manager
  - ../../base

configMapGenerator:
  - name: keycloak-realm
    behavior: merge
    files:
      - keycloak/realm-dev.json

images:
  - name: foodies-keycloak
    newTag: latest
  - name: foodies-webapp
    newTag: latest
  - name: foodies-menu
    newTag: latest
  - name: foodies-profile
    newTag: latest
  - name: foodies-basket
    newTag: latest
  - name: foodies-order
    newTag: latest
  - name: foodies-payment
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - start-dev
  - target:
      kind: PersistentVolumeClaim
      name: redis-data
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: hostpath
  - target:
      kind: PersistentVolumeClaim
      name: prometheus-data
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: hostpath
  - target:
      kind: RabbitmqCluster
      name: rabbitmq
    patch: |-
      - op: add
        path: /spec/persistence/storageClassName
        value: hostpath
  - target:
      kind: StatefulSet
      name: profile-postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: hostpath
  - target:
      kind: StatefulSet
      name: menu-postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: hostpath
  - target:
      kind: StatefulSet
      name: order-postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: hostpath
  - target:
      kind: StatefulSet
      name: payment-postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: hostpath
  - target:
      kind: StatefulSet
      name: keycloak-postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: hostpath
